server.port: 8080

mqtt:
  enabled: true
  host: tcp://182.92.159.33:1883
  userName: testgyjs
  pwd: testgyjs
  topic: '#'

spring:
  application:
    name: jpa-basic
  datasource:
    url: jdbc:mysql://localhost:3306/mqtt?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: shi666ge
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: MYSQL
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  #    dialect: org.hibernate.dialect.MySQL5InnoDBDialect;

#



